config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'sales_imports#index'
  resources :sales_imports do
    collection do
      post :import
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sales_import.rb
class SalesImport < ApplicationRecord

  def self.assign_from_row(row)
    sale = SalesImport.where(purchaser_name: row[:purchaser_name], item_description: row[:item_description], item_price: row[:item_price], purchase_count: row[:purchase_count], merchant_address: row[:merchant_address], merchant_name: row[:merchant_name], ).first_or_initialize
    sale.assign_attributes row.to_hash.slice(:purchaser_name, :item_description, :item_price, :purchase_count, :merchant_address, :merchant_name)
    sale
  end

  def self.import(file)
    counter = 0
    CSV.foreach(file.path, col_sep: "\t", headers: true, header_converters: :symbol) do |row|
      sale = SalesImport.assign_from_row(row)
      sale.total = sale.item_price * sale.purchase_count
      if sale.save
        counter += 1
      else
        # puts "#{sale.purchaser_name}"
      end
    end
    counter
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, :encrypted_password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/sales_imports_controller.rb
class SalesImportsController < ApplicationController
  def index
    @sales = SalesImport.paginate(:page => params[:page], per_page: 7)
    @total_value = SalesImport.all.sum(&:total)
  end

  def import
    count = SalesImport.import params[:file]
    redirect_to sales_imports_path, notice: "#{count} new sales entries"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_imports_helper.rb
module SalesImportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="sales_import.scss">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sales_imports/index.html.erb
<%= render 'shared/navbar' %>
<h1>Sales Imports</h1>
<div class="container">
  <div class="total-value">
    <p>Total Sales: $<%= @total_value %> </p>
  </div>
  <table id="table-head">
    <thead>
      <th>Purchaser Name</th>
      <th>Item Description</th>
      <th>Item Price</th>
      <th>Purchase Count</th>
      <th>Merchant Address</th>
      <th>Merchant Name</th>
      <th>Total</th>
    </thead>
    <p><%= @sales_totals %> </p>
    <tbody>
      <% @sales.each do |import| %>
      <tr>
        <td><%= import.purchaser_name %> </td>
        <td><%= import.item_description %> </td>
        <td><%= import.item_price %> </td>
        <td><%= import.purchase_count %> </td>
        <td><%= import.merchant_address %> </td>
        <td><%= import.merchant_name %> </td>
        <td><%= import.total %> </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <%= form_tag import_sales_imports_path, :class => "form", multipart: true do %>
    <%= file_field_tag :file, multiple: true %>
    <%= submit_tag "Upload"%>
  <% end %>
  <div class="paginate">
    <%= will_paginate @sales, class: "paginate" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-1">
  <img class="brand-logo" alt="Nuuvem" title="Nuuvem" src="//assets.nuuvem.com/assets/fe/images/nuuvem_logo-ab61ec645af3a6db7df0140d4792f31a.svg">
  <h2 class="title">Nuuvem Management System</h2>
  <ul>
    <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn-signout" %></li>
  </ul>
</div>